spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/bookshop
        username: postgres
        password: admin
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true

    security:
        user:
            name: admin
            password: 1234
server:
    port: 8082
    error:
        include-message: always